#!/usr/bin/env perl

use v5.26;
use lib 't/lib';

use File::Find  qw( find    );

for my $glob ( "t/bin/??-make-*" )
{
    local $ENV{ VERBOSE_FROMPERLVER } = '';
    local *STDOUT   = *STDERR;
    local $,        = "\n";

    print "Searching for setup: '$glob'\n";

    if( my @pathz = glob $glob )
    {
        print join "\n\t" => 'Setup paths:', @pathz;

        for my $path ( @pathz )
        {
            eval
            {
                -x $path    
                or die "Non-executable: '$path'\n";

                print "Execute: '$path'\n";

                my $output  = qx{ "$path" };

                die "Failed: '$path', $? ($!)\n$output"
                if $?;

                print "Complete: '$path'\n"
            }
            or
            warn;
        }
    }
    else
    {
        die "No setup paths found: '$glob'";
    }
}

my @found   = ();

my $wanted
= sub
{
    -f 
    and
    push @found, $File::Find::name
};

for my $path
(
    qw
    (
        version
        sandbox/.git
        t/dynamic
    )
)
{
    find $wanted, $path;
}


if( open my $fh, '>', 'MANIFEST' )
{
    print $fh <DATA>;
    print $fh join "\n" => @found, '';

    close $fh;
}
else
{
    die "Failed open: 'MANIFEST', $!";
}

# this is not a module
0
__DATA__
MANIFEST
README
CHANGES
Makefile.PL
lib/Module/FromPerlVer.pm

# fixed tests

t/00-usable.t
t/10-perl-version.t
t/11-env-version.t
t/12-path-version.t
t/13-reject-bogus-no-5.0.t

# root of dynamic tests

t/lib/Test/KwikHaks.pm

t/bin/20-file-defaults_t
t/bin/30-file-version-from_t

# dynamic files
